{
 "title": "EUCMonitoring",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_SiteName]] - [[col]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "SiteName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Worker-XdSessionInfo",
     "select": [
      [
       { "params": [ "ActiveSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Active" ], "type": "alias" }
      ],
      [
       { "params": [ "IdleSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Idle" ], "type": "alias" }
      ],
      [
       { "params": [ "DisconnectedSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Disconnected" ], "type": "alias" }
      ],
      [
       { "params": [ "TotalSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "[[tag_LicenseType]] License - [[col]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "LicenseType" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "XdLicensing-XDLicense",
     "select": [
      [
       { "params": [ "TotalAvailable" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Available" ], "type": "alias" }
      ],
      [
       { "params": [ "TotalIssued" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Issued" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "All Sites - Total Sessions",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Worker-XdSessionInfo",
     "select": [
      [
       { "params": [ "TotalSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Machines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_SiteName]] - Server - [[col]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "SiteName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Worker-XdServer",
     "query": "SELECT last(\"BrokerMachineRegistered\") AS \"Registered\", last(\"BrokerMachineUnRegistered\") AS \"Unregistered\", last(\"BrokerMachinesGood\") AS \"Good Health\", last(\"BrokerMachinesBad\") AS \"Bad Health\", last(\"BrokerMachineInMaintenance\") AS \"Maint Mode\" FROM \"Worker-XdServer\" WHERE $timeFilter GROUP BY time($__interval), \"SiteName\" fill(previous)",
     "select": [
      [
       { "params": [ "BrokerMachineRegistered" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Registered" ], "type": "alias" }
      ],
      [
       { "params": [ "BrokerMachineUnRegistered" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unregistered" ], "type": "alias" }
      ],
      [
       { "params": [ "BrokerMachineInMaintenance" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Maint Mode" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "[[tag_SiteName]] - Desktop - [[col]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "SiteName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Worker-XdDesktop",
     "select": [
      [
       { "params": [ "BrokerMachineRegistered" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Registered" ], "type": "alias" }
      ],
      [
       { "params": [ "BrokerMachineUnRegistered" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unregistered" ], "type": "alias" }
      ],
      [
       { "params": [ "BrokerMachineInMaintenance" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Maint Mode" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "[[tag_SiteName]] - Server - [[col]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "SiteName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Worker-XdServer",
     "query": "SELECT last(\"BrokerMachineRegistered\") AS \"Registered\", last(\"BrokerMachineUnRegistered\") AS \"Unregistered\", last(\"BrokerMachineInMaintenance\") AS \"Maint Mode\" FROM \"Worker-XdServer\" WHERE $timeFilter GROUP BY time($__interval), \"SiteName\" fill(previous)\n",
     "select": [
      [
       { "params": [ "BrokerMachinesGood" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Good Health" ], "type": "alias" }
      ],
      [
       { "params": [ "BrokerMachinesBad" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Bad Health" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "[[tag_SiteName]] - Desktop - [[col]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "SiteName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Worker-XdDesktop",
     "select": [
      [
       { "params": [ "BrokerMachinesGood" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Good Health" ], "type": "alias" }
      ],
      [
       { "params": [ "BrokerMachinesBad" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Bad Health" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gateway Connections",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_Server]] - [[col]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Server" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "NetscalerGateway-NetscalerGateway",
     "select": [
      [
       { "params": [ "TotalGatewayUsers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "ICAUsers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "ICA Users" ], "type": "alias" }
      ],
      [
       { "params": [ "VPNUsers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "VPN Users" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "vServer Health",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_vServerName]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vServerName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Netscaler-Netscaler",
     "select": [
      [
       { "params": [ "vServerHealth" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Directory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AD",
     "select": [
      [
       { "params": [ "State" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "App-V",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AppV",
     "select": [
      [
       { "params": [ "State" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cloud Connector",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CC",
     "select": [
      [
       { "params": [ "State" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Director",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Director",
     "select": [
      [
       { "params": [ "State" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FAS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FAS",
     "select": [
      [
       { "params": [ "State" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Netscaler",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Netscaler",
     "select": [
      [
       { "params": [ "State" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Netscaler Gateways",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NetscalerGateway",
     "select": [
      [
       { "params": [ "State" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Provisioning",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Provisioning",
     "select": [
      [
       { "params": [ "State" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SQL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SQL",
     "select": [
      [
       { "params": [ "State" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storefront",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Storefront",
     "select": [
      [
       { "params": [ "State" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "UPS",
     "select": [
      [
       { "params": [ "State" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "WEM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "WEM",
     "select": [
      [
       { "params": [ "State" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "XD Controllers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "XdControllers",
     "select": [
      [
       { "params": [ "State" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "XD Licensing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "XdLicensing",
     "select": [
      [
       { "params": [ "State" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}